### ISSUE TITLE
Couldn't preview or open certain files

### ISSUE THREAD

**Issue by FichteFoll** [FichteFoll/FileHistory#32]
Got a lot of these for the first two files in my list whenever I selected them:
```
Traceback (most recent call last):
  File "C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Packages\File History\file_history.py", line 733, in show_preview
    if self.get_view_from_another_group(selected_entry):
  File "C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Packages\File History\file_history.py", line 721, in get_view_from_another_group
    calling_group = FileHistory().calling_view_index[0]
IndexError: list index out of range
```
history entries (paths changed, but the unchanged paths exist):
```js
      {
        "filename": "E:\\...1.md", 
        "group": 0, 
        "timestamp": 1413416087, 
        "index": 3
      }, 
      {
        "filename": "E:\\...2.md", 
        "group": 1, 
        "timestamp": 1413416085, 
        "index": 0
      }, 
```

I then opened them manually, closed them again and now it works. Prolly not reproducable but wanted to write this down

**Comment by FichteFoll** [comment]
Unreproducable and the cause has most likely been fixed with the recent changes.
