### ISSUE TITLE
Absolute timestamp error

### ISSUE THREAD

**Issue by megadr01d** [FichteFoll/FileHistory#51]
Setting `"timestamp_relative": false` and calling the FileHistory panel, returns the following console error on ST Dev 3208:

```
Traceback (most recent call last):
  File "/Users/soulitude/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1050, in run_
    return self.run(**args)
  File "/Users/soulitude/Library/Application Support/Sublime Text 3/Installed Packages/File History.sublime-package/file_history.py", line 745, in run
AttributeError: 'OpenRecentlyClosedFileCommand' object has no attribute 'TIMESTAMP_FORMAT'
```

**Comment by FichteFoll** [comment]
Thanks for the report. Look like this has never worked in the first place and nobody realized because nobody uses it (or nobody reported it).

Released a new version with the fix.

**Comment by ghost** [comment]
Guess I never tried it before until now, but I was still wondering if could be related to ST.
Thanks for the fix, working now.
